name: Messaging Emulator Tests

on:
  pull_request:
    paths:
      - 'src/services/chat/chatService.ts'
      - 'src/services/__tests__/messaging.readReceipts.test.ts'
      - '.github/workflows/messaging-tests.yml'
  workflow_dispatch:

jobs:
  test-messaging:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java (for Firestore Emulator)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print Java version
        run: java -version

      - name: Install dependencies
        run: npm ci

      - name: Install rules testing utils
        run: npm i --no-save @firebase/rules-unit-testing@3.0.4


      - name: Run Messaging tests via Emulator
        env:
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
        run: npx firebase-tools --project demo-tradeya-messaging emulators:exec --only firestore "npx jest --runInBand --coverage=false --no-cache --testPathPattern=src/services/__tests__/messaging.readReceipts.test.ts"

